info.onCountdownEnd(function () {
    game.gameOver(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`Rayo`, function (sprite, location) {
    info.changeScoreBy(1)
    music.play(music.melodyPlayable(music.jumpUp), music.PlaybackMode.InBackground)
    tiles.setTileAt(location, sprites.castle.tileDarkGrass1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(false)
})
tiles.setCurrentTilemap(tilemap`nivel2`)
let Pikachu = sprites.create(assets.image`Pikachu`, SpriteKind.Player)
Pikachu.setStayInScreen(true)
Pikachu.setPosition(40, 25)
controller.moveSprite(Pikachu, 60, 60)
scene.cameraFollowSprite(Pikachu)
info.startCountdown(60)
let Cadaver = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(Cadaver, sprites.castle.tileGrass2)
Cadaver.follow(Pikachu)
Cadaver.setVelocity(1, 1)
forever(function () {
    if (info.score() == 3) {
        game.gameOver(true)
    }
})
